# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8
      - image: circleci/postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: jdbc:postgresql://localhost:5432/conf
          POSTGRES_PASSWORD: qwerty

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      
      - run: apt-get update -qq && apt-get install -y postgresql
      
      - run:  
          name: Set up DB
          command: |
            psql -h 127.0.0.1 -U postgres -c "CREATE DATABASE conf;"
            psql -h 127.0.0.1 -U postgres -c "CREATE USER postgres WITH PASSWORD 'qwerty'; GRANT ALL PRIVILEGES ON DATABASE conf TO postgres;"

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test
